version: 1.0
stages:
  Trial:
    jobs:
    - - custom-container
  
jobs:
  custom-container:
   type: custom-container
   parameters:
     scripts: 
     - touch temp.txt
     captureArtifacts:
     - temp.txt
     image: aws-cli-v1:latest
     
