version: 1.0
stages:
  StageOne:
    jobs:
    - - srcCheckout
    - - cppcmaketest
jobs:
  srcCheckout:
    description: ''
    type: source-checkout
    timeout: 30
    priority: major
    parameters:
      branch: master
  cppcmaketest:
    description: ''
    type: cpp-cmake
    timeout: 30
    priority: major
    parameters:
      image: cpp-cmake:latest
      scripts:
      - make --version
      - cmake .
      - make
      requiredArtifacts:
      - srcCheckout
